## q-METHOD Example Lecture VII
### slide 28

In [19]:
import numpy as np
from sys import path
path.append(
    "c:\\Users\\diego\\Dropbox\\Academic\\MEng Space Systems\\3. DOCA\\ADCS functions")
import ADCS_Functions as adcs
import ADCS_Functions_sym as adcs_sym

In [20]:
ub = np.matrix([np.sqrt(2)/2, -np.sqrt(2)/2, 0]).T
vb = np.matrix([np.sqrt(2)/2, np.sqrt(2)/2, 0]).T

ui = np.matrix([1, 0, 0]).T
vi = np.matrix([0, 1, 0]).T

adcs.print_matrix(np.array(ub)), adcs.print_matrix(
    np.array(vb)), adcs.print_matrix(np.array(ui)), adcs.print_matrix(np.array(vi))


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

(None, None, None, None)

In [21]:
ub, vb, ui, vi

(matrix([[ 0.70710678],
         [-0.70710678],
         [ 0.        ]]),
 matrix([[0.70710678],
         [0.70710678],
         [0.        ]]),
 matrix([[1],
         [0],
         [0]]),
 matrix([[0],
         [1],
         [0]]))

In [22]:
B = vb*vi.T+ub*ui.T
adcs.print_matrix(np.array(B))


<IPython.core.display.Math object>

In [23]:
k22 = np.trace(B)
k22

1.4142135623730951

In [24]:
K11 = B + B.T - k22*np.eye(3,3)
adcs.print_matrix(np.array(K11))


<IPython.core.display.Math object>

In [25]:
k12 = np.array([(B[1, 2] - B[2, 1]), (B[2, 0] - B[0, 2]), (B[0, 1] - B[1, 0])]).T
adcs.print_matrix(k12)


<IPython.core.display.Math object>

In [26]:
K = np.zeros((4,4))
K[0:3, 0:3] = K11
K[0:3, 3] = k12.T
K[3, 0:3] = k12.T
K[3, 3] = k22

adcs.print_matrix(K)


<IPython.core.display.Math object>

In [27]:
Eigenvalues, Eigenvectors = adcs.find_eig(K)
adcs.print_matrix(Eigenvalues), adcs.print_matrix(Eigenvectors)



<IPython.core.display.Math object>

<IPython.core.display.Math object>

(None, None)

In [28]:
max_Eigenvalue = np.max(Eigenvalues)
max_Eigenvector = Eigenvectors[:, np.where(Eigenvalues == np.max(Eigenvalues))]

adcs.print_matrix(np.array(np.matrix(max_Eigenvalue))),
adcs.print_matrix(np.array(np.matrix(max_Eigenvector)))


<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [29]:
C = adcs.Quaternion_to_DCM(max_Eigenvector)

adcs.print_matrix(C)

<IPython.core.display.Math object>

In [46]:
# using the library:

b = np.array([vb, ub])
RF = np.array([vi, ui])

B, k22, K11, k12, K, max_Eigenvalue, max_Eigenvector, C = adcs.q_method(b, RF)
adcs.print_matrix(B), adcs.print_matrix(K), adcs.print_matrix((max_Eigenvector)[:, 0]), adcs.print_matrix(C)


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

(None, None, None, None)

<IPython.core.display.Math object>

_____________________

## Example from Problem 1 of Lecture VII:

In [ ]:
#%% Data
# Define vectors
ne_eci = np.array([-1, 0, 0]).T
ns_eci = np.array([0, 1, 0]).T

#%% 1) Determine rotation matrix CbG from body coordinates to ECI coordinates.

# Define rotation matrix
CbG = np.array(adcs_sym.C3().subs("theta_3", np.pi/4)).astype(np.float64)

# Calculate body coordinates
ne_body = np.dot(CbG, ne_eci)
ns_body = np.dot(CbG, ns_eci)


In [ ]:
vb, ub, vi, ui = ne_body, ns_body, ne_eci, ns_eci
B, k22, K11, k12, K, max_Eigenvalue, max_Eigenvector, C = adcs.q_method(
    vb, ub, vi, ui)
adcs.print_matrix(C)


TypeError: q_method() takes from 2 to 3 positional arguments but 4 were given

In [ ]:
adcs.print_matrix(B)
adcs.print_matrix(K)
