# A program to convert between reference frames using directional cosine matrices.

In [2]:
#%% Import libraries
import numpy as np
import sys
sys.path.append(
   "c:\\Users\\diego\\Dropbox\\Academic\\MEng Space Systems\\3. DOCA\\ADCS functions")
import ADCS_Functions as adcs
# from math import sin, cos, pi


In [3]:
#%% Data
# Assume three reference frames A, B and I.
# Let the two reference frames A and B be defined relative to the inertial reference frame I by the orthonormal unit base vectors.

a1, a2, a3 = np.array([1/2, np.sqrt(3)/2, 0]), np.array([0,
                                                         0, 1]), np.array([np.sqrt(3)/2, -1/2, 0])
b1, b2, b3 = np.array([0, 1, 0]), np.array([1, 0, 0]), np.array([0, 0, -1])

a = np.matrix([a1, a2, a3]).T
b = np.matrix([b1, b2, b3]).T

a, b


(matrix([[ 0.5      ,  0.       ,  0.8660254],
         [ 0.8660254,  0.       , -0.5      ],
         [ 0.       ,  1.       ,  0.       ]]),
 matrix([[ 0,  1,  0],
         [ 1,  0,  0],
         [ 0,  0, -1]]))

In [4]:
# where the ai and bi (i = 1, 2, 3) vector components are written in the inertial frame I.
# Note that the unit base vectors of the inertial frame are:

i1, i2, i3 = np.array([1, 0, 0]), np.array([0, 1, 0]), np.array([0, 0, 1])

i = np.matrix([i1, i2, i3]).T
i

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [5]:
#%% (a) Check that the unit base vectors ai respectively bi (i = 1, 2, 3) build an orthonormal reference frame.

print(np.dot(a1, a2) == 0)
print(np.dot(a2, a3) == 0)
print(np.dot(a1, a3) == 0)

print(np.allclose(np.dot(a1, a1), 1))
print(np.allclose(np.dot(a2, a2), 1))
print(np.allclose(np.dot(a3, a3), 1))


True
True
True
True
True
True


In [6]:
print(np.dot(b1, b2) == 0)
print(np.dot(b2, b3) == 0)
print(np.dot(b1, b3) == 0)

print(np.allclose(np.dot(b1, b1), 1))
print(np.allclose(np.dot(b2, b2), 1))
print(np.allclose(np.dot(b3, b3), 1))

True
True
True
True
True
True


In [7]:
#%% (b) Find the directional cosine matrix Cab that describes the orientation of frame A relative to frame B
Cab = np.array([[np.dot(a1, b1), np.dot(a1, b2), np.dot(a1, b3)],
                [np.dot(a2, b1), np.dot(a2, b2), np.dot(a2, b3)],
                [np.dot(a3, b1), np.dot(a3, b2), np.dot(a3, b3)]])

Cab

array([[ 0.8660254,  0.5      ,  0.       ],
       [ 0.       ,  0.       , -1.       ],
       [-0.5      ,  0.8660254,  0.       ]])

Or just use my custom library:

In [8]:
Cab = adcs.DCM_A_B(a, b)
Cab


matrix([[ 0.8660254,  0.5      ,  0.       ],
        [ 0.       ,  0.       , -1.       ],
        [-0.5      ,  0.8660254,  0.       ]])

In [9]:
#%% (c) Find the directional cosine matrix Cai that describes the orientation of frame A relative to frame I
Cai = adcs.DCM_A_B(a, i)
Cai

matrix([[ 0.5      ,  0.8660254,  0.       ],
        [ 0.       ,  0.       ,  1.       ],
        [ 0.8660254, -0.5      ,  0.       ]])

In [10]:
#%% (d) Find the directional cosine matrix Cab that describes the orientation of frame B relative to frame I
Cbi = adcs.DCM_A_B(b, i)
Cbi

matrix([[ 0,  1,  0],
        [ 1,  0,  0],
        [ 0,  0, -1]])

In [11]:
#%% (e) Check if Cab = Cai*(Cbi).T holds
np.allclose(Cab, Cai@(Cbi.T))

True

In [12]:
#%% (f) Check if Cab*(Cab).T = I
np.allclose(Cab@(Cab.T), np.eye(3))

True

In [13]:
#%% (g) For given arbitrary matrix A and matrix B check if they do not commute (AB != BA)
A = Cai
B = (Cbi).T
np.allclose(A@B, B@A)

False

In [14]:
#%% (h) Is the following matrix C = [1/2, 0, 0; 0, 1, 0; 0, 0, 2] a rotation matrix?
C = np.matrix([[1/2, 0, 0],
               [0, 1, 0],
               [0, 0, 2]])
print(np.allclose(C@C.T, 1))


False


$C C^T = 1$ for a rotation matrix